version: "3.7"

services:
    postgres:
        image: postgres:latest
        restart: always
        ports:
          - 10432:5432
        volumes:
            - "${PWD}/config/run/postgres-setup.sql:/docker-entrypoint-initdb.d/gogs-init.sql"
            - "${DB_DATA_PATH}:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-root
        secrets:
            - postgres-root

    gogs:
        image: gogs/gogs:latest
        restart: always
        ports:
            - 10022:22
            - 10080:3000
        volumes:
            - "${GOGS_DATA_PATH}:/data"
            - "${CERTS_PATH}:/app/gogs/certs"
        environment:
            - RUN_CROND=true
        depends_on:
            - postgres

secrets:
    postgres-root:
        external: true

