version: "3.7"
services:
    postgres:
        image: postgres:latest
        restart: always
        ports:
          - 10432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./init/run/postgres-setup.sql:/docker-entrypoint-initdb.d/gogs-init.sql
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrests/postgres-root
        secrets:
            - postgres-root

    gogs:
        image: gogs/gogs:latest
        restart: always
        ports:
            - 10022:22
            - 10080:3000
        volumes:
            - gogs-data:/data
            - ${CERTS_PATH}:/app/gogs/certs
        environment:
            - RUN_CROND=true
        depends_on:
            - postgres

volumes:
    db-data:
        driver: local
        driver_opts:
            type: bind
            device: ${DB_DATA_PATH}
    gogs-data:
        driver: local
        driver_opts:
            type: bind
            device: ${GOGS_DATA_PATH}

secrets:
    postgres-root:
        file: ./secrets/postgres-root

